import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import MainNavigation from '../components/layout/main-navigation';
import { getServerSession } from 'next-auth';
import Provider from '../components/providers/session-provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={inter.className} suppressHydrationWarning={true}>
        <Provider session={session}>
          <MainNavigation children={children} />
        </Provider>
      </body>
    </html>
  );
}
