import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import MainNavigation from '../components/layout/main-navigation';
import { AuthProvider } from '@/components/providers/auth-provider';
import { ApolloClient, ApolloProvider } from '@apollo/client';
import client from '@/components/providers/apollo-client';
import { ApolloProviderWrapper } from '@/components/providers/apollo-provider';
import Guard from '@/components/guard/guard';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={inter.className} suppressHydrationWarning={true}>
        {/* <AuthProvider> */}
        <ApolloProviderWrapper>{children}</ApolloProviderWrapper>
        {/* </AuthProvider> */}
      </body>
    </html>
  );
}
